In [ ]:
import torch
print(torch.__version__)

1.12.0+cu116


In [1]:
import sys
print(sys.version)

3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]


In [ ]:
import gdown

# a file
url = "https://drive.google.com/uc?id=1l_5RK28JRL19wpT22B-DY9We3TVXnnQQ"
output = "test"

# same as the above, and you can copy-and-paste a URL from Google Drive with fuzzy=True
url = "https://drive.google.com/file/d/0B9P1L--7Wd2vNm9zMTJWOGxobkU/view?usp=sharing"
gdown.download(url=url, output=output, fuzzy=True, verify=False)

In [1]:
#my version
import gdown
import os

# 设置 HTTP 代理
os.environ['http_proxy'] = 'http://127.0.0.1:2333'

# 设置 HTTPS 代理
os.environ['https_proxy'] = 'http://127.0.0.1:2333'

url = 'https://drive.google.com/file/d/1yo98AklzKwfTworgiC646j8cMrVxCNSH/view?usp=drive_link'
output = "test"
gdown.download(url=url, output=output, fuzzy=True,proxy="http://127.0.0.1:2333", verify=False,use_cookies=False)

Using proxy: http://127.0.0.1:2333


/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


FileURLRetrievalError: Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1yo98AklzKwfTworgiC646j8cMrVxCNSH

but Gdown can't. Please check connections and permissions.

In [ ]:
import gdown

# a file
url = "https://drive.google.com/uc?id=1l_5RK28JRL19wpT22B-DY9We3TVXnnQQ"
output = "test"
# same as the above, and you can copy-and-paste a URL from Google Drive with fuzzy=True
url = "https://drive.google.com/file/d/0B9P1L--7Wd2vNm9zMTJWOGxobkU/view?usp=sharing"
gdown.download(url=url, output=output, fuzzy=True)

# Cached download with identity check via MD5 (or SHA1, SHA256, etc).
# Pass postprocess function e.g., extracting compressed file.
md5 = "md5:fa837a88f0c40c513d975104edf3da17"
gdown.cached_download(url, output, hash=hash, postprocess=gdown.extractall)

# a folder
url = "https://drive.google.com/drive/folders/15uNXeRBIhVvZJIhL4yTw4IsStMhUaaxl"
gdown.download_folder(url)

# same as the above, but with the folder ID
id = "15uNXeRBIhVvZJIhL4yTw4IsStMhUaaxl"
gdown.download_folder(id=id)

In [20]:
import numpy as np

# 定义示例数据
skinning_weights = np.array([[[1, 2], [3, 4], [5, 6]]])  # 形状为 (1, 3, 2)
bv = np.array([[0, 0, 0,0,0]])  # 形状为 (1, 5)
p_idx = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],  # 示例数据，形状为 (3, 24)
                   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
                   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

# 选择指定的权重
result = skinning_weights[bv, p_idx[..., 0], :]

print("选择出来的权重矩阵：")
print(result)


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (1,5) (3,) 

In [19]:
p_idx=p_idx.reshape(-1,3)
print(p_idx)
p_idx[..., 0]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([ 0,  3,  6,  9, 12, 15, 18, 21,  0,  3,  6,  9, 12, 15, 18, 21,  0,
        3,  6,  9, 12, 15, 18, 21])